### ISSUE TITLE
D365 connection error in Visual Studio 2022 V17.10 

### ISSUE THREAD

**Issue by josephmcmac** [josephmcmac/JM-Dataverse-Toolbelt#380]
If the latest 17.10 version of visual studio is installed, the extension cannot connect to the D365 web services due to the following internal error being thrown: Could not load file or assembly 'Microsoft.VisualStudio.Extensibility.Contracts, Version=17.10.2083.0

The earlier Visual Studio version 17.8 still works, so to use the extension, Visual Studio needs to be reverted to Version 17.8 by uninstalling, then installing the earlier version from a download at the link below

https://learn.microsoft.com/en-us/visualstudio/releases/2022/release-history

**Comment by phuocle** [comment]
Yes. My extension get the same problem too.

**Comment by phuocle** [comment]
I update to version **17.10.3** and now it worked

**Comment by josephmcmac** [comment]
Confirmed as fixed in Visual Studio version 17.10.3
